session:
  redisUrl: redis:6379
  redisDB: 10
db:
  url: postgres://postgres@postgres:5432/golang_example_development?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
grpc:
  services:
    products:
      target: product_service:50051
      maxConn: 10
      initConn: 1
      maxLifeDuration: 5m
      idleTimeout: 1s
  clientParameters:
    time: 5m
    timeout: 10s
    permitWithoutStream: false
oauth:
  redisUrl: redis:6379
  redisDB: 10
  clientStoreInfo:
    123456:
      id: 123456
      secret: 12345678
      domain: http://localhost:9094
auth:
  services:
    test-service: 1
  relativePath: keys/local
logger:
  debug: true
graphql:
  introspection: true
tracing:
  jaeger:
    reporter:
      localAgentHostPort: jaeger:6831
    disabled: false
    serviceName: golang-example-app-server
