session:
  redisUrl: 127.0.0.1:6379
  redisDB: 10
db:
  url: postgresql://localhost:5432/golang_example_development?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
oauth:
  redisUrl: 127.0.0.1:6379
  redisDB: 10
logger:
  debug: true
graphql:
  introspection: true
tracing:
  jaeger:
    disabled: false
    serviceName: golang-example-app-server
