session:
  redisUrl: 127.0.0.1:6379
  redisDB: 10
db:
  url: postgresql://localhost:5432/oauth2_development?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
oauth:
  redisUrl: 127.0.0.1:6379
  redisDB: 10
logger:
  debug: true
graphql:
  introspection: true
